AppProFi/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import *

urlpatterns = [
    path('', inicio, name= "Inicio" ),
    path('lista-torneos/', TorneoList.as_view(), name= "ListaTorneos" ),
    path('detalle-torneo/<pk>', TorneoDetail.as_view(), name= "DetalleTorneo" ),
    path('crear-torneo/', TorneoCreate.as_view(), name= "CrearTorneo" ),
    path('actualizar-torneo/<pk>', TorneoUpdate.as_view(), name= "ActualizarTorneo" ),
    path('eliminar-torneo/<pk>', TorneoDelete.as_view(), name= "EliminarTorneo" ),
    path('lista-equipos/', EquipoList.as_view(), name= "ListaEquipos" ),
    path('detalle-equipo/<pk>', EquipoDetail.as_view(), name= "DetalleEquipo" ),
    path('crear-equipo/', EquipoCreate.as_view(), name= "CrearEquipo" ),
    path('actualizar-equipo/<pk>', EquipoUpdate.as_view(), name= "ActualizarEquipo" ),
    path('eliminar-equipo/<pk>', EquipoDelete.as_view(), name= "EliminarEquipo" ),
    path('lista-jugadores/', JugadorList.as_view(), name= "ListaJugadores" ),
    path('detalle-jugador/<pk>', JugadorDetail.as_view(), name= "DetalleJugador" ),
    path('crear-jugador/', JugadorCreate.as_view(), name= "CrearJugador" ),
    path('actualizar-jugador/<pk>', JugadorUpdate.as_view(), name= "ActualizarJugador"),
    path('eliminar-jugador/<pk>', JugadorDelete.as_view(), name= "EliminarJugador" ),
    path('lista-entrenadores/', EntrenadorList.as_view(), name= "ListaEntrenadores" ),
    path('detalle-entrenador/<pk>', EntrenadorDetail.as_view(), name= "DetalleEntrenador" ),
    path('crear-entrenador/', EntrenadorCreate.as_view(), name= "CrearEntrenador" ),
    path('actualizar-entrenador/<pk>', EntrenadorUpdate.as_view(), name= "ActualizarEntrenador" ),
    path('eliminar-entrenador/<pk>', EntrenadorDelete.as_view(), name= "EliminarEntrenador" ),
    path('login/', loginView, name= "Login"),
    path('logout/', LogoutView.as_view(template_name="logout.html"), name= "Logout"),
    path('editar-perfil/', editar_perfil, name= "EditarPerfil"),
    path('registrar/', register, name= "Registrar"),
    path('editar-avatar/<pk>', AvatarEdit.as_view(), name= "EditarAvatar" ),
]

ProFi/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500



from AppProFi.views import about,inicio

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app-profi/', include('AppProFi.urls')),
    path('about/',about, name="AboutMe" ),
    path('',inicio, name="Inicio" ),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

AppProFi/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Torneo(models.Model):

    nombre= models.CharField(max_length=30)
    cantidad_equipos= models.IntegerField()
    premio= models.CharField(max_length=30)
    fecha_comienzo= models.DateField()
    imagen= models.ImageField(upload_to='torneos',null=True,blank=True)
    
    class Meta():
        verbose_name= "Tournament"
        verbose_name_plural= "Tournaments"

    def __str__(self):
        return f"{self.nombre}"

class Equipo(models.Model):

    nombre= models.CharField(max_length=30)
    barrio= models.CharField(max_length=30)
    titulos= models.IntegerField()
    division= models.CharField(max_length=10)
    torneo = models.ManyToManyField(Torneo,blank=True)
    imagen= models.ImageField(upload_to='equipos',null=True,blank=True)

    class Meta():
        verbose_name= "Team"
        verbose_name_plural= "Teams"
    
    def __str__(self):
        return f"{self.nombre}"

class Jugador(models.Model):
    
    nombre= models.CharField(max_length=30)
    apellido= models.CharField(max_length=30)
    edad= models.IntegerField()
    equipo= models.ForeignKey(Equipo,on_delete=models.CASCADE)
    posicion= models.CharField(max_length=2)
    imagen= models.ImageField(upload_to='jugadores',null=True,blank=True)

    class Meta():
        verbose_name= "Player"
        verbose_name_plural= "Players"

    def __str__(self):
        return f"{self.apellido}, {self.nombre}, {self.equipo}"

class Entrenador(models.Model):
        
    nombre= models.CharField(max_length=30)
    apellido= models.CharField(max_length=30)
    edad= models.IntegerField()
    equipo= models.ForeignKey(Equipo,on_delete=models.CASCADE)
    titulos= models.IntegerField()
    imagen= models.ImageField(upload_to='entrenadores',null=True,blank=True)

    class Meta():
        verbose_name= "Coach"
        verbose_name_plural= "Coaches"

    def __str__(self):
        return f"{self.apellido}, {self.nombre}"

class Avatar(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', blank=True, null=True)

AppProFi/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User

from .models import *

class TorneoFormulario(forms.ModelForm):

    class Meta:
        model= Torneo
        fields= ('__all__')

class Equipo(forms.ModelForm):

    class Meta:
        model= Equipo
        fields= ('__all__')

class JugadorFormulario(forms.ModelForm):

    class Meta:
        model= Jugador
        fields= ('__all__')

class EntrenadorFormulario(forms.ModelForm):

    class Meta:
        model= Entrenador
        fields= ('__all__')

class UserEditForm(UserChangeForm):

    password = forms.CharField(
        help_text="",
        widget=forms.HiddenInput(), required=False
    )

    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repita contraseña", widget=forms.PasswordInput)

    class Meta:
        model=User
        fields=('email', 'first_name', 'last_name', 'password1', 'password2')

    def clean_password2(self):
        password2 = self.cleaned_data["password2"]
        if password2 != self.cleaned_data["password1"]:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return password2

class AvatarFormulario(forms.ModelForm):

    class Meta:
        model=Avatar
        fields=('__all__')

AppProFi/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required

from .models import Torneo, Equipo, Jugador, Entrenador, Avatar
from .forms import  UserEditForm


# Create your views here.

def inicio(req):
    return render(req,"index.html",{"mensaje":"Bienvenido a InfoTorneos"})

def about(req):

    return render(req,"about.html")


class TorneoList(ListView):
    paginate_by= 3
    model= Torneo
    template_name="torneo_list.html"
    context_object_name="torneos"

class TorneoDetail(DetailView):
    model= Torneo
    template_name="torneo_detalle.html"
    context_object_name="torneo"

@method_decorator(staff_member_required, name='dispatch')
class TorneoCreate(CreateView):
    model= Torneo
    template_name="torneo_crear.html"
    fields=('__all__')
    success_url="/app-profi/lista-torneos/"

@method_decorator(staff_member_required, name='dispatch')
class TorneoUpdate(UpdateView):
    model= Torneo
    template_name="torneo_actualizar.html"
    fields= ('__all__')
    success_url="/app-profi/lista-torneos/"

@method_decorator(staff_member_required, name='dispatch')
class TorneoDelete(DeleteView):
    model= Torneo
    template_name="torneo_eliminar.html"
    success_url= "/app-profi/lista-torneos/"

class EquipoList(ListView):
    model= Equipo
    template_name="equipo_list.html"
    context_object_name="equipos"


class EquipoDetail(DetailView):
    model= Equipo
    template_name="equipo_detalle.html"
    context_object_name="equipo"
    
@method_decorator(staff_member_required, name='dispatch')
class EquipoCreate(CreateView):
    model= Equipo
    template_name="equipo_crear.html"
    fields=('__all__')
    success_url="/app-profi/lista-equipos/"

@method_decorator(staff_member_required, name='dispatch')
class EquipoUpdate(UpdateView):
    model= Equipo
    template_name="equipo_actualizar.html"
    fields= ('__all__')
    success_url="/app-profi/lista-equipos/"

@method_decorator(staff_member_required, name='dispatch')
class EquipoDelete(DeleteView):
    model= Equipo
    template_name="equipo_eliminar.html"
    success_url= "/app-profi/lista-equipos/"

class JugadorList(ListView):
    model= Jugador
    template_name="jugador_list.html"
    context_object_name="jugadores"

class JugadorDetail(DetailView):
    model= Jugador
    template_name="jugador_detalle.html"
    context_object_name="jugador"

@method_decorator(staff_member_required, name='dispatch')
class JugadorCreate(CreateView):
    model= Jugador
    template_name="jugador_crear.html"
    fields=('__all__')
    success_url="/app-profi/lista-jugadores/"

@method_decorator(staff_member_required, name='dispatch')
class JugadorUpdate(UpdateView):
    model= Jugador
    template_name="jugador_actualizar.html"
    fields= ('__all__')
    success_url="/app-profi/lista-jugadores/"

@method_decorator(staff_member_required, name='dispatch')
class JugadorDelete(DeleteView):
    model= Jugador
    template_name="jugador_eliminar.html"
    success_url= "/app-profi/lista-jugadores/"

class EntrenadorList(ListView):
    model= Entrenador
    template_name="entrenador_list.html"
    context_object_name="entrenadores"

class EntrenadorDetail(DetailView):
    model= Entrenador
    template_name="entrenador_detalle.html"
    context_object_name="entrenador"

@method_decorator(staff_member_required, name='dispatch')
class EntrenadorCreate(CreateView):
    model= Entrenador
    template_name="entrenador_crear.html"
    fields=('__all__')
    success_url="/app-profi/lista-entrenadores/"

@method_decorator(staff_member_required, name='dispatch')
class EntrenadorUpdate(UpdateView):
    model= Entrenador
    template_name="entrenador_actualizar.html"
    fields= ('__all__')
    success_url="/app-profi/lista-entrenadores/"

@method_decorator(staff_member_required, name='dispatch')
class EntrenadorDelete(DeleteView):
    model= Entrenador
    template_name="entrenador_eliminar.html"
    success_url= "/app-profi/lista-entrenadores/"


def loginView(req):

    if req.method == 'POST':

        miFormulario = AuthenticationForm(req, data=req.POST)

        if miFormulario.is_valid():

            data= miFormulario.cleaned_data
            usuario= data["username"]
            psw= data["password"]
            user= authenticate(username=usuario, password=psw)

            if user:
                login(req, user)
                return render(req, "index.html", {"mensaje": f"Bienvenido {usuario}"})
            else:
                return render(req, "index.html", {"mensaje": "Datos incorrectos"})
            
        else:
            return render(req, "index.html", {"mensaje": "Formulario inválido"})
        
    else:
        miFormulario= AuthenticationForm()
        return render(req, "login.html", {"miFomulario": miFormulario})

def register(req):

    if req.method == 'POST':

        miFormulario = UserCreationForm(req.POST)
        if miFormulario.is_valid():
            data= miFormulario.cleaned_data
            usuario= data["username"]
            miFormulario.save()
            return render(req, "index.html", {"mensaje": f"Usuario {usuario} creado con éxito!"})
        else:
            return render(req, "index.html", {"mensaje": "Formulario inválido"})
    else:
        miFormulario = UserCreationForm()
        return render(req, "registro.html", {"miFomulario": miFormulario})
    
def editar_perfil(req):

    usuario= req.user

    try:
        if req.method == 'POST':

            miFormulario = UserEditForm(req.POST, instance=req.user)

            if miFormulario.is_valid():
                
                data = miFormulario.cleaned_data
                usuario.first_name= data["first_name"]
                usuario.last_name= data["last_name"]
                usuario.email= data["email"]
                usuario.set_password(data["password1"])
                usuario.save()
                return render(req, "index.html", {"mensaje": "Perfil actualizado con éxito"})
            else:
                return render(req, "editar_perfil.html", {"miFomulario": miFormulario})
        else:
            miFormulario= UserEditForm(instance=req.user)
            return render(req, "editar_perfil.html", {"miFomulario": miFormulario})
    except:
        return render(req,"index.html",{"mensaje":"Debes logearte primero."})

    
class AvatarEdit(UpdateView):

    model= Avatar
    template_name="editar_avatar.html"
    fields= ("imagen",)
    success_url="/app-profi/editar-perfil/"


class StaffRequiredMixin(object):
    @method_decorator(staff_member_required)
    def dispatch(self,req,*args,**kwargs):
        return super(StaffRequiredMixin,self.dispatch(req,*args,**kwargs))
    

AppProFi/templates/about.html
{% extends 'index.html' %}


{% block ContenidoQueCambia %}

    <h1>Federico D'Angelo Rodríguez</h1>
    <p>Hola, soy el creador de esta web. Estoy comenzando en el mundo de la programación, y ésta es mi primera experiencia web.</p>
    <p>
        Esta página es la base para en un futuro poder crear una web estilo GranDT, donde el usuario pueda elegir sus preferencias
        de equipos,jugadores, y también poder participar de un prode por fecha.
    </p>
{% endblock ContenidoQueCambia %}
    

AppProFi/templates/editar_perfil.html
{% extends 'index.html' %}

{% block ContenidoQueCambia %}
    
    <form action="{% url 'EditarPerfil' %}" method="post">{% csrf_token %}

        {{miFomulario.as_p}}

        <button type="submit">Actualizar</button>
    </form>
    
    <a href="{% url 'EditarAvatar' user.id %}">Editar avatar</a>

        
    
{% endblock ContenidoQueCambia %}

AppProFi/templates/entrenador_actualizar.html
{% extends 'index.html' %}


{% block ContenidoQueCambia %}
    
<form action="{% url 'ActualizarEntrenador' entrenador.id%}" enctype="multipart/form-data" method="post">{% csrf_token %}

    {{form.as_p}}

    <button type="submit">Enviar</button>
</form>

{% endblock ContenidoQueCambia %}
    

AppProFi/templates/entrenador_crear.html
{% extends 'index.html' %}


{% block ContenidoQueCambia %}
    
<form action="{% url 'CrearEntrenador' %}" enctype="multipart/form-data" method="post">{% csrf_token %}

    {{form.as_p}}

    <button type="submit">Enviar</button>
</form>

{% endblock ContenidoQueCambia %}
    

AppProFi/templates/entrenador_list.html
{% extends 'index.html' %}


{% block ContenidoQueCambia %}

<section class="lista-pages">
    {% if entrenadores %}             
            {% for entrenador in entrenadores %}
            <div class="card" style="width: 18rem;">
                {% if entrenador.imagen %}
                    <img style="width: 280px;" class="card-img-top" src="{{entrenador.imagen.url}}" alt="">
                {% endif %}
                <div class="card-body">  
                    <h5 class="card-title" >{{entrenador.nombre}}</h5>  
                    <a href="{% url 'DetalleEntrenador' entrenador.id %}" class="btn btn-primary">{{entrenador.nombre}}</a>
                </div>
            </div>
            {% endfor %}
    {% endif %}
</section>
<div>
    <a class="btn btn-primary" href="{% url 'CrearEntrenador' %}">Crear entrenador</a>
</div>

<div class="pagination justify-content-center">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
        {% endif %}

        <span class="current">
            Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.  
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
        {% endif %}
    </span>
</div>

{% endblock ContenidoQueCambia %}
    

AppProFi/templates/equipo_crear.html
{% extends 'index.html' %}


{% block ContenidoQueCambia %}
    
<form action="{% url 'CrearEquipo' %}" enctype="multipart/form-data" method="post">{% csrf_token %}

    {{form.as_p}}

    <button type="submit">Enviar</button>
</form>

{% endblock ContenidoQueCambia %}
    

AppProFi/templates/equipo_eliminar.html
{% extends 'index.html' %}


{% block ContenidoQueCambia %}
    
<form method="post">{% csrf_token %}

    <p>Está seguro de eliminar el equipo?</p>

    <button type="submit">Confirmar</button>
    <button><a href="{% url 'ListaEquipos' %}">Cancelar</a></button>
</form>


{% endblock ContenidoQueCambia %}
    

AppProFi/templates/jugador_crear.html
{% extends 'index.html' %}


{% block ContenidoQueCambia %}
    
<form action="{% url 'CrearJugador' %}" enctype="multipart/form-data" method="post">{% csrf_token %}

    {{form.as_p}}

    <button type="submit">Enviar</button>
</form>

{% endblock ContenidoQueCambia %}
    

AppProFi/templates/jugador_eliminar.html
{% extends 'index.html' %}


{% block ContenidoQueCambia %}
    
<form method="post">{% csrf_token %}

    <p>Está seguro de eliminar el jugador?</p>

    <button type="submit">Confirmar</button>
    <button><a href="{% url 'ListaJugadores' %}">Cancelar</a></button>
</form>


{% endblock ContenidoQueCambia %}
    

AppProFi/templates/jugador_list.html
{% extends 'index.html' %}


{% block ContenidoQueCambia %}

<section class="lista-pages">
    {% if jugadores %}             
            {% for jugador in jugadores %}
            <div class="card" style="width: 18rem;">
                {% if jugador.imagen %}
                    <img style="width: 280px;" class="card-img-top" src="{{jugador.imagen.url}}" alt="">
                {% endif %}
                <div class="card-body">  
                    <h5 class="card-title" >{{jugador.nombre}}</h5>  
                    <a href="{% url 'DetalleJugador' jugador.id %}" class="btn btn-primary">{{jugador.nombre}}</a>
                </div>
            </div>
            {% endfor %}
    {% endif %}
</section>
<div>
    <a class="btn btn-primary" href="{% url 'CrearJugador' %}">Crear Jugador</a>
</div>
<div class="pagination justify-content-center">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
        {% endif %}
    </span>
</div>

{% endblock ContenidoQueCambia %}

    

AppProFi/templates/login.html
{% extends 'index.html' %}


{% block ContenidoQueCambia %}
    
<form action="" method="post">{% csrf_token %}

    {{miFomulario.as_p}}

    <button type="submit">Iniciar Sesión</button>
</form>


{% endblock ContenidoQueCambia %}
    

AppProFi/templates/logout.html
{% extends 'index.html' %}


{% block ContenidoQueCambia %}
    <h1>Gracias por su Visita !!</h1>
{% endblock ContenidoQueCambia %}
    

AppProFi/templates/torneo_actualizar.html
{% extends 'index.html' %}


{% block ContenidoQueCambia %}
    
<form action="{% url 'ActualizarTorneo' torneo.id%}" enctype="multipart/form-data" method="post">{% csrf_token %}

    {{form.as_p}}

    <button type="submit">Enviar</button>
</form>

{% endblock ContenidoQueCambia %}
    

AppProFi/templates/torneo_detalle.html
{% extends 'index.html' %}


{% block ContenidoQueCambia %}
<table class="table">
    <thead style="font-size: x-large;">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nombre</th>
        <th scope="col">Equipos</th>
        <th scope="col">Premio</th>
        <th scope="col">Fecha de comienzo</th>
        {% if torneo.imagen %}
          <th></th>
        {% endif %} 
        <th scope="col">Editar</th>
        <th scope="col">Eliminar</th>
    </tr>
    </thead>
    <tbody style="font-size: x-large;">
      <tr>
        <th scope="row">Torneo</th>
        <td>{{torneo.nombre}}</td>
        <td>
            <button  class="btn btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample">
              Equipos
            </button>
            <div style="min-height: 120px;font-size: large;">
                <div class="collapse collapse-horizontal" id="collapseWidthExample" style="background-color:transparent">
                  <div class="card" style="width: 300px;background-color:transparent">
                        {% for u in torneo.equipo_set.all  %}
                            <ul class="list-group">
                            <li style="background-color:brown;color: white;" class="list-group-item">{{u.nombre}}</li>
                            </ul>
                        {% endfor %}
                  </div>
                </div>
            </div>
          </td>
        <td>{{torneo.premio}}</td>
        <td>{{torneo.fecha_comienzo}}</td>
        {% if torneo.imagen %}
            <td><img style="width: 280px;" class="card-img-top" src="{{torneo.imagen.url}}" alt=""></td>
        {% endif %}
        <td>
          <a class="btn btn-secondary" href="{% url 'ActualizarTorneo' torneo.id %}">Editar</a></td>
        <td>
          <a class="btn btn-danger" href="{% url 'EliminarTorneo' torneo.id %}">Eliminar</a></td> 
      </tr>
      <tr>
      </tr>
    </tbody>
</table>

{% endblock ContenidoQueCambia %}
    